# Use the latest alpine as the base image
FROM alpine:latest

# Set the working directory inside the container
WORKDIR /app

# Update package lists and install necessary dependencies
RUN apk update && apk add bash curl sudo

# Copy the script into the container
COPY wireguard-manager.sh /app/wireguard-manager.sh

# Grant execution permissions to the script
RUN chmod +x /app/wireguard-manager.sh

# Execute the script during build
RUN /bin/bash /app/wireguard-manager.sh --install
